[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "build/"
  functions = "functions/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"